apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azurefile-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: csi-drivers
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: charts/latest/azurefile-csi-driver
    targetRevision: HEAD
    repoURL: https://github.com/kubernetes-sigs/azurefile-csi-driver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
