apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  destination:
    namespace: datadog
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: "datadog-secret"
          clusterName: "home"
          logs:
            enabled: true
            containerCollectAll: true
          processAgent:
            processCollection: true
    path: charts/datadog
    targetRevision: HEAD
    repoURL: https://github.com/DataDog/helm-charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
